name: Test checkout

on:
  pull_request:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository }}
      - run: echo ${{ secrets.GH_TOKEN }}
  log-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: b-bly/private-test
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}
          path: 'private-test'
      - run: ls

