name: issue_comment

on:
  issue_comment:

jobs:
  log-comment:
    runs-on: ubuntu-latest
    steps:
      - name: check out pr data
        run: |
          echo "${{ github.event.issue.pull_request.base_ref }}"
          echo "${{ github.event.issue.pull_request.head_ref }}"
          echo "${{ github.event.issue.pull_request.headRef }}"
          echo "${{ github.event.issue.pull_request.commits }}"
          echo "${{ github.event.issue }}"
          echo 'headRef'

