name: issue_comment

on:
  issue_comment:
  pull_request:

jobs:
  log-comment:
    runs-on: ubuntu-latest
    steps:
      # - name: check out pr data
      #   run: |
      #     echo "${{ github.event.issue.pull_request.base_ref }}"
      #     echo "${{ github.event.issue.pull_request.head_ref }}"
      #     echo "${{ github.event.issue.pull_request.headRef }}"
      #     echo "${{ github.event.issue.pull_request.commits }}"
      #     echo "${{ toJSON(github.event.issue) }}"
      #     echo 'headRef'
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
      - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
      # - name: Get pr with github-script
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       pr=github.rest.pulls.get({
      #         pull_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #       })
      #       echo 'echo pr'
      #       echo $pr
      #       echo 'toJSON'
      #       echo toJSON($pr)
      - uses: actions/github-script@v3
        id: get-pr
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
