name: issue_comment

on:
  issue_comment:
  pull_request:

jobs:
  log-comment:
    runs-on: ubuntu-latest
    steps:
      # - name: check out pr data
      #   run: |
      #     echo "${{ github.event.issue.pull_request.base_ref }}"
      #     echo "${{ github.event.issue.pull_request.head_ref }}"
      #     echo "${{ github.event.issue.pull_request.headRef }}"
      #     echo "${{ github.event.issue.pull_request.commits }}"
      #     echo "${{ toJSON(github.event.issue) }}"
      #     echo 'headRef'
      # - uses: 8BitJonny/gh-get-current-pr@2.1.3
      #   id: PR
      # - run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
      - name: Get pr with github-script
        uses: actions/github-script@v6
        with:
          script: |
            echo "${{ toJSON(context) }}"
          # pr=github.rest.pulls.get({
          #   pull_number: context.issue.number,
          #   owner: context.repo.owner,
          #   repo: context.repo.repo,
          # })
          # echo 'echo pr'
          # echo $pr
          # echo 'toJSON'
          # echo toJSON($pr)
